version: '3.1'

services:

  web:
    image: php:7.0-apache
    container_name: web
    volumes:
    - ./src:/var/www/html
    ports:
    - "80:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - /sessions
    external_links:
      - db:db
    depends_on:
      - db
    logging:
      driver: "none"

  db:
    image: mariadb
    container_name: db
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - edb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret1
      MYSQL_DATABASE: lic
      MYSQL_USER: lic
      MYSQL_PASSWORD: 6M9j9P4q

  enigma:
    build: .
    container_name: enigma
    restart: always
    ports:
      - "9999:9999"
    links:
      - db
    depends_on:
      - db

  volumes:
    edb:
