version: '3.1'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    volumes:
      - /sessions
    external_links:
      - db:db
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./lic.sql:/docker-entrypoint-initdb.d/lic.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret1
      MYSQL_DATABASE: lic
      MYSQL_USER: lic
      MYSQL_PASSWORD: 6M9j9P4q